edc.iam.sts.oauth.token.url=https://keycloak:8080/auth/realms/basyx/protocol/openid-connect/token
edc.iam.sts.oauth.client.id=edc-control-plane
edc.iam.sts.oauth.client.secret.alias=edc-control-plane-secret
edc.transfer.proxy.token.signer.privatekey.alias=edc-transfer-proxy-token-signer-privatekey
edc.transfer.proxy.token.verifier.publickey.alias=edc-transfer-proxy-token-verifier-publickey
edc.datasource.default.url=jdbc:postgresql://postgres:5432/edc
edc.datasource.default.user=edc
edc.datasource.default.password=edc
edc.vault.hashicorp.url=http://vault:8200
edc.vault.hashicorp.token=root
edc.participant.context.id=e24c6fb0-9a15-4c18-8dca-d65e9f7821de
web.http.management.host=0.0.0.0
web.http.management.port=8182
web.http.management.path=/api/management
edc.dpf.selector.url=http://edc-controlplane:19193/api/management/v3/dataplanes
tx.edc.dataplane.token.refresh.endpoint=https://${HOST_ADDRESS}:19291/api/public/token
