edc.iam.sts.oauth.token.url=https://keycloak:8080/auth/realms/basyx/protocol/openid-connect/token
edc.iam.sts.oauth.client.id=edc-control-plane
edc.iam.sts.oauth.client.secret=edc-control-plane-secret
edc.iam.sts.oauth.client.secret.alias=edc-control-plane-secret
edc.transfer.proxy.token.signer.privatekey.alias=edc-transfer-proxy-token-signer-privatekey
edc.transfer.proxy.token.verifier.publickey.alias=edc-transfer-proxy-token-verifier-publickey
edc.datasource.default.url=jdbc:postgresql://postgres:5432/edc
web.http.protocol.host=0.0.0.0
web.http.protocol.port=19191
web.http.protocol.path=/api/dsp
web.http.management.host=0.0.0.0
web.http.management.port=19193
web.http.management.path=/api/management
edc.dsp.callback.address=https://${HOST_ADDRESS}:19191/api/dsp
edc.dataplane.api.public.baseurl=https://${HOST_ADDRESS}:19291/api/public
edc.vault.hashicorp.url=http://vault:8200
edc.vault.hashicorp.token=root
edc.datasource.default.user=edc
edc.datasource.default.password=edc
edc.participant.id=did:web:${HOST_ADDRESS}
edc.participant.context.id=226d238b-4b27-4936-9fc4-1664504784aa
tractusx.edc.participant.bpn=BPNL000000000001
tx.edc.iam.dcp.bdrs.server.url=https://${HOST_ADDRESS}:8443
