basyx:
  cors:
    allowed-origins:
      - "https://*"
    allowed-methods:
      - "GET"
      - "POST"
      - "PATCH"
      - "DELETE"
      - "PUT"
      - "OPTIONS"
      - "HEAD"
    allowed-headers:
      - "Authorization"
      - "Content-Type"
      - "Accept"
  feature:
    authorization:
      enabled: false
      type: rbac
      jwtBearerTokenProvider: keycloak
      rbac:
        file: file:/workspace/config/rbac_rules.json

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: aas-registry
      username: mongoAdmin
      password: mongoPassword
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/auth/realms/basyx/protocol/openid-connect/certs
