edc.iam.sts.oauth.token.url=http://keycloak:8080/auth/realms/basyx/protocol/openid-connect/token
edc.iam.sts.dim.url=http://dim-mock:9080/auth/realms/basyx/protocol/openid-connect/token
edc.iam.sts.dim.client.id=edc-control-plane-secondary
edc.iam.sts.dim.client.secret=edc-control-plane-secret
edc.iam.issuer.id=did:web:edc-dataplane-secondary
edc.iam.sts.oauth.client.id=edc-dataplane-secondary
edc.iam.sts.oauth.client.secret=edc-dataplane-secret
edc.hostname=edc-dataplane-secondary
edc.iam.sts.oauth.client.secret.alias=edc-dataplane-secret
edc.participant.id=did:web:${HOST_ADDRESS}:secondary
edc.participant.context.id=6d3aa004-b5e3-4ec6-aca8-2d2b0f37e0d9
tractusx.edc.participant.bpn=BPNL000000000002
tx.edc.iam.dcp.bdrs.server.url=http://bdrs-mock-secondary:9081
tx.iam.iatp.bdrs.server.url=http://bdrs-mock-secondary:9081
edc.transfer.proxy.token.signer.privatekey.alias=edc-transfer-proxy-token-signer-privatekey
edc.transfer.proxy.token.verifier.publickey.alias=edc-transfer-proxy-token-verifier-publickey
web.http.port=29290
web.http.path=/api
web.http.public.host=0.0.0.0
web.http.public.port=29291
web.http.public.path=/api/public
web.http.dataplane.port=29292
web.http.dataplane.path=/api/dataplane
web.http.control.port=29293
web.http.control.path=/api/control
edc.dataplane.api.public.baseurl=http://${HOST_ADDRESS}:29291/api/public
tx.edc.dataplane.token.refresh.endpoint=http://${HOST_ADDRESS}:29291/api/public/token
edc.dpf.selector.url=http://edc-controlplane:29194/api/control/v1/dataplanes
edc.dataplane.selector.url=http://edc-controlplane:29194/api/control/v1/dataplanes
edc.datasource.default.url=jdbc:postgresql://postgres:5432/edc-secondary
edc.datasource.default.user=edc-user
edc.datasource.default.password=edc
edc.vault.hashicorp.url=http://vault:8200
edc.vault.hashicorp.token=root
