edc.iam.sts.oauth.token.url=http://keycloak:8080/auth/realms/basyx/protocol/openid-connect/token
# edc.iam.sts.dim.url=http://dim-mock:8080/auth/realms/basyx/protocol/openid-connect/token
# edc.iam.sts.dim.client.id=edc-control-plane-secondary
# edc.iam.sts.dim.client.secret=edc-control-plane-secret
edc.iam.sts.dim.url=http://dim-mock:9080/auth/realms/basyx/protocol/openid-connect/token
edc.iam.sts.dim.client.id=edc-control-plane-secondary
edc.iam.sts.dim.client.secret=edc-control-plane-secret
edc.iam.issuer.id=did:web:edc-controlplane-secondary
edc.iam.sts.oauth.client.id=edc-control-plane-secondary
edc.iam.sts.oauth.client.secret=edc-control-plane-secret
edc.iam.sts.oauth.client.secret.alias=edc-control-plane-secret
edc.transfer.proxy.token.signer.privatekey.alias=edc-transfer-proxy-token-signer-privatekey
edc.transfer.proxy.token.verifier.publickey.alias=edc-transfer-proxy-token-verifier-publickey
edc.datasource.default.url=jdbc:postgresql://postgres:5432/edc-secondary
edc.sql.schema.autocreate=true
edc.sql.store.schema.autocreate=true
edc.sql.store.contractnegotiation.schema.autocreate=true
edc.sql.store.transferprocess.schema.autocreate=true
edc.sql.store.policymonitor.schema.autocreate=true
edc.sql.store.asset.schema.autocreate=true
edc.sql.store.contractdefinition.schema.autocreate=true
edc.sql.store.policydefinition.schema.autocreate=true
edc.sql.store.contractnegotiation.autocreate=true
edc.sql.store.transferprocess.autocreate=true
edc.sql.store.policymonitor.autocreate=true
edc.sql.store.asset.autocreate=true
edc.sql.store.contractdefinition.autocreate=true
edc.sql.store.policydefinition.autocreate=true
web.http.protocol.host=0.0.0.0
web.http.protocol.port=29191
web.http.protocol.path=/api/dsp
web.http.default.host=0.0.0.0
web.http.default.port=29192
web.http.default.path=/api
web.http.control.host=0.0.0.0
web.http.control.port=29194
web.http.control.path=/api/control
edc.control.endpoint=http://edc-controlplane:29194/api/control
web.http.management.host=0.0.0.0
web.http.management.port=29193
web.http.management.path=/api/management
edc.api.auth.key=password
edc.dsp.callback.address=https://${HOST_ADDRESS}:29191/api/dsp
edc.dataplane.api.public.baseurl=https://${HOST_ADDRESS}:29291/api/public
edc.vault.hashicorp.url=http://vault:8200
edc.vault.hashicorp.token=root
edc.datasource.default.user=edc-user
edc.datasource.default.password=edc
edc.participant.id=did:web:${HOST_ADDRESS}:secondary
edc.participant.context.id=9ac6477e-7fbb-4d5d-b19f-26b9bbac9c42
tractusx.edc.participant.bpn=BPNL000000000002
# tx.edc.iam.dcp.bdrs.server.url=http://bdrs-mock-secondary:8081
# tx.iam.iatp.bdrs.server.url=http://bdrs-mock-secondary:8081
tx.edc.iam.dcp.bdrs.server.url=http://bdrs-mock:8081
tx.iam.iatp.bdrs.server.url=http://bdrs-mock:8081