"""Package validated company step-2 AAS environments as AASX files."""

from __future__ import annotations

import argparse
import datetime
import io
import json
import shutil
from pathlib import Path
from typing import Any
from urllib.parse import urlsplit
from urllib.parse import quote, unquote

from excel_to_aasx.logging import generated, warning

SUPPORTED_KEY_TYPES = {
    "AnnotatedRelationshipElement",
    "AssetAdministrationShell",
    "BasicEventElement",
    "Blob",
    "Capability",
    "ConceptDescription",
    "DataElement",
    "Entity",
    "EventElement",
    "File",
    "FragmentReference",
    "GlobalReference",
    "Identifiable",
    "MultiLanguageProperty",
    "Operation",
    "Property",
    "Range",
    "Referable",
    "ReferenceElement",
    "RelationshipElement",
    "Submodel",
    "SubmodelElement",
    "SubmodelElementCollection",
    "SubmodelElementList",
}
BASYX_KEY_TYPES = SUPPORTED_KEY_TYPES - {"Identifiable", "Referable"}


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    generated(path)


def shell_id(environment: dict[str, Any]) -> str:
    shells = environment.get("assetAdministrationShells", [])
    if len(shells) != 1:
        raise ValueError(f"expected exactly one AAS shell, got {len(shells)}")
    identifier = shells[0].get("id")
    if not identifier:
        raise ValueError("AAS shell has no id")
    return identifier


def normalize_for_basyx(payload: Any) -> None:
    if isinstance(payload, dict):
        if payload.get("idShort") == "":
            payload.pop("idShort", None)
        keys = payload.get("keys")
        if isinstance(keys, list):
            for key in keys:
                if isinstance(key, dict) and key.get("type") not in BASYX_KEY_TYPES:
                    key["type"] = "GlobalReference"
                    payload["type"] = "ExternalReference"
        qualifiers = payload.get("qualifiers")
        if isinstance(qualifiers, list):
            seen: set[str] = set()
            unique = []
            for qualifier in qualifiers:
                qualifier_type = qualifier.get("type") if isinstance(qualifier, dict) else None
                if qualifier_type and qualifier_type in seen:
                    continue
                if qualifier_type:
                    seen.add(qualifier_type)
                unique.append(qualifier)
            payload["qualifiers"] = unique
        if payload.get("modelType") == "SubmodelElementList":
            value = payload.get("value")
            if isinstance(value, list):
                for item in value:
                    if isinstance(item, dict):
                        item.pop("idShort", None)
        value = payload.get("value")
        if isinstance(value, list) and payload.get("modelType") in {
            "SubmodelElementCollection",
            "Entity",
        }:
            seen_idshorts: set[str] = set()
            unique_values = []
            for item in value:
                if not isinstance(item, dict) or "modelType" not in item:
                    unique_values.append(item)
                    continue
                id_short = item.get("idShort")
                if id_short and id_short in seen_idshorts:
                    continue
                if id_short:
                    seen_idshorts.add(id_short)
                unique_values.append(item)
            payload["value"] = unique_values
        for value in payload.values():
            normalize_for_basyx(value)
    elif isinstance(payload, list):
        for item in payload:
            normalize_for_basyx(item)


def is_external_file_reference(value: str) -> bool:
    scheme = urlsplit(value).scheme.lower()
    return scheme in {"http", "https", "ftp", "mailto", "urn", "data"}


def aasx_package_path(value: str) -> str:
    if value.startswith("/") and len([part for part in value.split("/") if part]) > 1:
        return value
    normalized = unquote(value).lstrip("/").strip().strip(".")
    if not normalized:
        normalized = "missing-file"
    return "/aasx/files/" + quote(normalized, safe="._-")


def placeholder_bytes(name: str, content_type: str) -> bytes:
    if content_type == "application/pdf":
        return b"%PDF-1.4\n% dummy generated by AAS pipeline\n1 0 obj\n<<>>\nendobj\ntrailer\n<<>>\n%%EOF\n"
    if content_type == "image/png":
        return (
            b"\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01"
            b"\x08\x06\x00\x00\x00\x1f\x15\xc4\x89\x00\x00\x00\rIDATx\x9cc\xf8\xff"
            b"\xff?\x00\x05\xfe\x02\xfeA\xe2!\xbc\x00\x00\x00\x00IEND\xaeB`\x82"
        )
    if content_type in {"image/jpeg", "image/jpg"}:
        return b"\xff\xd8\xff\xd9"
    return f"Dummy supplementary file generated for missing reference: {name}\n".encode("utf-8")


def collect_missing_supplementary_files(payload: Any) -> list[dict[str, str]]:
    records: list[dict[str, str]] = []
    if isinstance(payload, dict):
        if payload.get("modelType") == "File":
            value = str(payload.get("value") or "").strip()
            if value and not is_external_file_reference(value):
                package_path = aasx_package_path(value)
                payload["value"] = package_path
                records.append(
                    {
                        "path": package_path,
                        "originalPath": value,
                        "contentType": str(payload.get("contentType") or "text/plain"),
                        "reason": "File reference is local/relative but no source file is available; placeholder added to AASX.",
                    }
                )
        for value in payload.values():
            records.extend(collect_missing_supplementary_files(value))
    elif isinstance(payload, list):
        for item in payload:
            records.extend(collect_missing_supplementary_files(item))
    deduplicated: dict[str, dict[str, str]] = {}
    for record in records:
        deduplicated.setdefault(record["path"], record)
    return list(deduplicated.values())


def build_file_store(missing_files: list[dict[str, str]]) -> Any:
    from basyx.aas.adapter import aasx

    file_store = aasx.DictSupplementaryFileContainer()
    for record in missing_files:
        file_store.add_file(
            record["path"],
            io.BytesIO(placeholder_bytes(record["path"], record["contentType"])),
            record["contentType"],
        )
        warning(
            "DUMMY supplementary file generated: "
            f"path={record['path']} contentType={record['contentType']} "
            "reason=referenced file missing"
        )
    return file_store


def package_workbook(workbook_dir: Path, output_dir: Path) -> dict[str, Any]:
    from basyx.aas import model
    from basyx.aas.adapter import aasx
    from basyx.aas.adapter.json import read_aas_json_file
    from pyecma376_2 import OPCCoreProperties

    environment_path = workbook_dir / "environment.json"
    environment = load_json(environment_path)
    aas_id = shell_id(environment)

    workbook_output = output_dir / workbook_dir.name
    workbook_output.mkdir(parents=True, exist_ok=True)

    json_output = workbook_output / "environment.json"
    aasx_output = workbook_output / f"{workbook_dir.name}.aasx"
    packaged_environment = json.loads(json.dumps(environment))
    normalize_for_basyx(packaged_environment)
    missing_files = collect_missing_supplementary_files(packaged_environment)
    file_store = build_file_store(missing_files)
    write_json(json_output, packaged_environment)

    object_store = read_aas_json_file(json_output, failsafe=False)
    with aasx.AASXWriter(aasx_output) as writer:
        writer.write_aas(
            aas_ids=[aas_id],
            object_store=object_store,
            file_store=file_store,
        )
        metadata = OPCCoreProperties()
        metadata.creator = "AAS Understanding Project"
        metadata.created = datetime.datetime.now(datetime.timezone.utc)
        writer.write_core_properties(metadata)

    roundtrip_store: model.DictObjectStore[model.Identifiable] = model.DictObjectStore()
    with aasx.AASXReader(aasx_output) as reader:
        reader.read_into(roundtrip_store, aasx.DictSupplementaryFileContainer())
    if roundtrip_store.get_identifiable(aas_id) is None:
        raise RuntimeError(f"AASX roundtrip did not contain {aas_id}")

    return {
        "workbook": workbook_dir.name,
        "shellId": aas_id,
        "json": str(json_output),
        "aasx": str(aasx_output),
        "aasxSizeBytes": aasx_output.stat().st_size,
        "roundtrip": "ok",
        "dummySupplementaryFiles": missing_files,
        "packagingNotes": [
            "The Step 4 JSON copy is normalized for BaSyx SDK compatibility.",
            "Duplicate qualifier types are de-duplicated.",
            "Unsupported reference key types are converted to ExternalReference/GlobalReference.",
            "Direct SubmodelElementList item idShort values are removed.",
            "Duplicate sibling idShort values in collections are de-duplicated."
        ],
    }


def publish_aasx_collection(output_dir: Path, summaries: list[dict[str, Any]]) -> list[dict[str, Any]]:
    collection_dir = output_dir.parent / "aasx"
    collection_dir.mkdir(parents=True, exist_ok=True)
    published = []
    for summary in summaries:
        source = Path(summary["aasx"])
        target = collection_dir / source.name
        shutil.copy2(source, target)
        generated(target)
        published.append(
            {
                "workbook": summary["workbook"],
                "source": str(source),
                "aasx": str(target),
                "aasxSizeBytes": target.stat().st_size,
            }
        )
    return published


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-dir", type=Path, required=True)
    parser.add_argument("--validation-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    return parser.parse_args()


def assert_validated(workbook_dir: Path, validation_dir: Path) -> None:
    report_path = validation_dir / workbook_dir.name / "validation-report.json"
    report = load_json(report_path)
    errors = report.get("issueCounts", {}).get("error", 0)
    warnings = report.get("issueCounts", {}).get("warning", 0)
    if errors or warnings:
        raise RuntimeError(
            f"{workbook_dir.name} is not cleanly validated: "
            f"{errors} errors, {warnings} warnings"
        )


def main() -> None:
    args = parse_args()
    summaries = []
    for workbook_dir in sorted(args.input_dir.iterdir()):
        if not workbook_dir.is_dir():
            continue
        assert_validated(workbook_dir, args.validation_dir)
        summaries.append(package_workbook(workbook_dir, args.output_dir))
    published_aasx = publish_aasx_collection(args.output_dir, summaries)
    write_json(
        args.output_dir / "summary.json",
        {"workbooks": summaries, "publishedAasx": published_aasx},
    )
    write_json(args.output_dir.parent / "aasx" / "summary.json", {"aasx": published_aasx})


if __name__ == "__main__":
    main()
